"""Normalized source-of-truth for the attached MCM Scientific Instrument v0.2."""

METADATA = {'schema_version': 'MCM_IMPORT_DOCX_1.1',
 'instrument_name_ar': 'نضج MCM',
 'instrument_name_en': 'Marketing Communication Maturity',
 'instrument_code': 'MCM',
 'version': '0.2',
 'status': 'EXPERT_REVIEW',
 'validation_status': 'PROVISIONAL_NOT_VALIDATED',
 'default_scale': 'LIKERT_5_EXTENT',
 'language': 'AR_EN',
 'reference_period': 'PAST_12_MONTHS',
 'allow_not_applicable': 'YES',
 'not_applicable_code': 'NOT_APPLICABLE',
 'allow_dont_know': 'YES',
 'dont_know_code': 'DONT_KNOW',
 'core_item_count': '43',
 'total_item_count': '67',
 'notes': 'Literature-informed researcher-developed items; not verbatim adopted; expert review version'}

SCALE_DEFINITIONS = {'LIKERT_5_EXTENT': [{'value': 1, 'label_ar': 'لا تنطبق إطلاقًا', 'label_en': 'Does not apply at all'},
                     {'value': 2, 'label_ar': 'تنطبق بدرجة قليلة', 'label_en': 'Applies to a small extent'},
                     {'value': 3, 'label_ar': 'تنطبق بدرجة متوسطة', 'label_en': 'Applies to a moderate extent'},
                     {'value': 4, 'label_ar': 'تنطبق بدرجة كبيرة', 'label_en': 'Applies to a great extent'},
                     {'value': 5,
                      'label_ar': 'تنطبق بدرجة كبيرة جدًا',
                      'label_en': 'Applies to a very great extent'}],
 'RELATIVE_5_COMPETITOR': [{'value': 1,
                            'label_ar': 'أضعف بكثير من المنافسين الرئيسيين',
                            'label_en': 'Much worse than major competitors'},
                           {'value': 2,
                            'label_ar': 'أضعف من المنافسين الرئيسيين',
                            'label_en': 'Worse than major competitors'},
                           {'value': 3,
                            'label_ar': 'مماثل للمنافسين الرئيسيين',
                            'label_en': 'Similar to major competitors'},
                           {'value': 4,
                            'label_ar': 'أفضل من المنافسين الرئيسيين',
                            'label_en': 'Better than major competitors'},
                           {'value': 5,
                            'label_ar': 'أفضل بكثير من المنافسين الرئيسيين',
                            'label_en': 'Much better than major competitors'}]}

DIMENSIONS = [{'code': 'EN01',
  'construct': 'ENABLER',
  'name_ar': 'دعم القيادة',
  'name_en': 'Leadership Support',
  'display_order': 1,
  'weight': 1.0,
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R05;R14;R03'},
 {'code': 'EN02',
  'construct': 'ENABLER',
  'name_ar': 'الكفاءات البشرية',
  'name_en': 'Human Competencies',
  'display_order': 2,
  'weight': 1.0,
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R14;R03'},
 {'code': 'EN03',
  'construct': 'ENABLER',
  'name_ar': 'البنية التحتية التقنية',
  'name_en': 'Technology Infrastructure',
  'display_order': 3,
  'weight': 1.0,
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R13'},
 {'code': 'EN04',
  'construct': 'ENABLER',
  'name_ar': 'جاهزية البيانات',
  'name_en': 'Data Readiness',
  'display_order': 4,
  'weight': 1.0,
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R06;R07'},
 {'code': 'MCM01',
  'construct': 'MCM',
  'name_ar': 'الحوكمة والتوجيه الاستراتيجي للاتصال',
  'name_en': 'Strategic Communication Governance & Direction',
  'display_order': 101,
  'weight': 1.0,
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R01;R03;R04'},
 {'code': 'MCM02',
  'construct': 'MCM',
  'name_ar': 'ذكاء أصحاب المصلحة والسياق',
  'name_en': 'Stakeholder & Context Intelligence',
  'display_order': 201,
  'weight': 1.0,
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R01;R02;R05'},
 {'code': 'MCM03',
  'construct': 'MCM',
  'name_ar': 'حوكمة المعلومات والنزاهة الاتصالية',
  'name_en': 'Communication Information Governance & Integrity',
  'display_order': 301,
  'weight': 1.0,
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R06;R07'},
 {'code': 'MCM04',
  'construct': 'MCM',
  'name_ar': 'التنسيق التنظيمي ورحلة العميل',
  'name_en': 'Organisational & Journey Orchestration',
  'display_order': 401,
  'weight': 1.0,
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R01;R04;R08'},
 {'code': 'MCM05',
  'construct': 'MCM',
  'name_ar': 'مواءمة الوعد والتجربة والتوقعات',
  'name_en': 'Promise–Experience & Expectation Alignment',
  'display_order': 501,
  'weight': 1.0,
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R08;R09;R26'},
 {'code': 'MCM06',
  'construct': 'MCM',
  'name_ar': 'الأدلة والتعلم والاتصال التكيفي',
  'name_en': 'Evidence, Learning & Adaptive Communication',
  'display_order': 601,
  'weight': 1.0,
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R05;R10;R17'},
 {'code': 'MCM07',
  'construct': 'MCM',
  'name_ar': 'الاستدامة وقابلية التوسع الاتصالي',
  'name_en': 'Institutionalisation & Communication Scalability',
  'display_order': 701,
  'weight': 1.0,
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R11;R12;R13'},
 {'code': 'SMCE01',
  'construct': 'SMCE',
  'name_ar': 'كفاءة الاستجابة والحل',
  'name_en': 'Response & Resolution Efficiency',
  'display_order': 1101,
  'weight': 1.0,
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R15;R16'},
 {'code': 'SMCE02',
  'construct': 'SMCE',
  'name_ar': 'جودة المعنى والتفاعل',
  'name_en': 'Meaning & Interaction Quality',
  'display_order': 1201,
  'weight': 1.0,
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R02;R04'},
 {'code': 'SMCE03',
  'construct': 'SMCE',
  'name_ar': 'كفاءة الانتقال إلى الفعل',
  'name_en': 'Action Efficiency',
  'display_order': 1301,
  'weight': 1.0,
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R03;R17'},
 {'code': 'SMCE04',
  'construct': 'SMCE',
  'name_ar': 'انخفاض الاحتكاك الاتصالي',
  'name_en': 'Low Communication Friction',
  'display_order': 1401,
  'weight': 1.0,
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R08;R16;R26'},
 {'code': 'SMCE05',
  'construct': 'SMCE',
  'name_ar': 'كفاءة الموارد وتحقيق الأهداف',
  'name_en': 'Resource & Goal Efficiency',
  'display_order': 1501,
  'weight': 1.0,
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R14;R17'},
 {'code': 'OUT01',
  'construct': 'OUTCOME',
  'name_ar': 'الثقة',
  'name_en': 'Stakeholder Trust',
  'display_order': 2101,
  'weight': 1.0,
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R18'},
 {'code': 'OUT02',
  'construct': 'OUTCOME',
  'name_ar': 'رضا العملاء',
  'name_en': 'Customer Satisfaction',
  'display_order': 2201,
  'weight': 1.0,
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R19'},
 {'code': 'OUT03',
  'construct': 'OUTCOME',
  'name_ar': 'نتائج العلامة التجارية',
  'name_en': 'Brand Outcomes / Perceived Brand Equity',
  'display_order': 2301,
  'weight': 1.0,
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R20'},
 {'code': 'OUT04',
  'construct': 'OUTCOME',
  'name_ar': 'أداء الأعمال',
  'name_en': 'Business Performance',
  'display_order': 2401,
  'weight': 1.0,
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R14;R21'}]

ITEMS = [{'code': 'EN01_01',
  'dimension_code': 'EN01',
  'construct': 'ENABLER',
  'prompt_ar': 'تدعم القيادة العليا بصورة واضحة تطوير الاتصال التسويقي وتحسينه المستمر.',
  'prompt_en': 'Senior leadership clearly supports the development and continuous improvement of marketing '
               'communication.',
  'display_order': 1,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'ENABLER_DIAGNOSTIC',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R05;R14;R03',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'EN01_02',
  'dimension_code': 'EN01',
  'construct': 'ENABLER',
  'prompt_ar': 'توفر القيادة العليا توجيهًا واضحًا لأولويات الاتصال التسويقي.',
  'prompt_en': 'Senior leadership provides clear direction for marketing communication priorities.',
  'display_order': 2,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'ENABLER_DIAGNOSTIC',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R05;R03',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'EN01_03',
  'dimension_code': 'EN01',
  'construct': 'ENABLER',
  'prompt_ar': 'تمنح القيادة المسؤولين عن الاتصال الصلاحيات اللازمة لتنفيذ القرارات المعتمدة.',
  'prompt_en': 'Senior leadership grants communication decision owners the authority needed to implement approved '
               'decisions.',
  'display_order': 3,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'ENABLER_DIAGNOSTIC',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R05;R14',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'EN02_01',
  'dimension_code': 'EN02',
  'construct': 'ENABLER',
  'prompt_ar': 'يمتلك المسؤولون عن الاتصال المهارات اللازمة لتخطيط الاتصال التسويقي بصورة منهجية.',
  'prompt_en': 'People responsible for communication have the skills needed to plan marketing communication '
               'systematically.',
  'display_order': 11,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'ENABLER_DIAGNOSTIC',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R14;R03',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'EN02_02',
  'dimension_code': 'EN02',
  'construct': 'ENABLER',
  'prompt_ar': 'يمتلك المسؤولون عن الاتصال المهارات اللازمة لتنفيذ الأنشطة الاتصالية عبر القنوات المناسبة.',
  'prompt_en': 'People responsible for communication have the skills needed to execute communication activities '
               'across appropriate channels.',
  'display_order': 12,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'ENABLER_DIAGNOSTIC',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R14;R03',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'EN02_03',
  'dimension_code': 'EN02',
  'construct': 'ENABLER',
  'prompt_ar': 'يمتلك المسؤولون عن الاتصال القدرة على تفسير بيانات الأداء واستخدامها لتحسين الاتصال.',
  'prompt_en': 'People responsible for communication can interpret performance data and use it to improve '
               'communication.',
  'display_order': 13,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'ENABLER_DIAGNOSTIC',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R14;R10',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'EN03_01',
  'dimension_code': 'EN03',
  'construct': 'ENABLER',
  'prompt_ar': 'تتوفر أنظمة تقنية تدعم تنفيذ الاتصال التسويقي وتنسيقه عبر القنوات ذات الصلة.',
  'prompt_en': 'Technology systems are available to support the execution and coordination of marketing '
               'communication across relevant channels.',
  'display_order': 21,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'ENABLER_DIAGNOSTIC',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R13',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'EN03_02',
  'dimension_code': 'EN03',
  'construct': 'ENABLER',
  'prompt_ar': 'تستطيع الأنظمة التقنية ذات الصلة تبادل المعلومات اللازمة لدعم الاتصال دون اعتماد مفرط على النقل '
               'اليدوي.',
  'prompt_en': 'Relevant technology systems can exchange information needed for communication without excessive '
               'reliance on manual transfer.',
  'display_order': 22,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'ENABLER_DIAGNOSTIC',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R13',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'EN03_03',
  'dimension_code': 'EN03',
  'construct': 'ENABLER',
  'prompt_ar': 'تتيح البنية التقنية تتبع التفاعلات أو الحالات المهمة للعملاء عبر نقاط الاتصال الرقمية.',
  'prompt_en': 'The technology infrastructure enables tracking of important customer interactions or states across '
               'digital touchpoints.',
  'display_order': 23,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'ENABLER_DIAGNOSTIC',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R13;R08',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'EN04_01',
  'dimension_code': 'EN04',
  'construct': 'ENABLER',
  'prompt_ar': 'تتوفر للمنظمة بيانات حديثة بما يكفي لدعم القرارات الاتصالية.',
  'prompt_en': 'The organisation has data that are sufficiently current to support communication decisions.',
  'display_order': 31,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'ENABLER_DIAGNOSTIC',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R06;R07',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'EN04_02',
  'dimension_code': 'EN04',
  'construct': 'ENABLER',
  'prompt_ar': 'تتوفر للمنظمة بيانات موثوقة بما يكفي لدعم القرارات الاتصالية.',
  'prompt_en': 'The organisation has data that are sufficiently reliable to support communication decisions.',
  'display_order': 32,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'ENABLER_DIAGNOSTIC',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R06',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'EN04_03',
  'dimension_code': 'EN04',
  'construct': 'ENABLER',
  'prompt_ar': 'يمكن للفرق المعنية الوصول إلى البيانات اللازمة للاتصال واستخدامها عند الحاجة.',
  'prompt_en': 'Relevant teams can access and use the data needed for communication when required.',
  'display_order': 33,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'ENABLER_DIAGNOSTIC',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R06;R07',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM01_01',
  'dimension_code': 'MCM01',
  'construct': 'MCM',
  'prompt_ar': 'ترتبط قرارات الاتصال التسويقي بأهداف تنظيمية ونتائج محددة بوضوح.',
  'prompt_en': 'Marketing communication decisions are linked to clearly defined organisational goals and outcomes.',
  'display_order': 101,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R01;R03;R04',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM01_02',
  'dimension_code': 'MCM01',
  'construct': 'MCM',
  'prompt_ar': 'توجد مسؤوليات وصلاحيات واضحة لاتخاذ القرارات المتعلقة بالاتصال التسويقي.',
  'prompt_en': 'Clear responsibilities and decision rights exist for marketing communication decisions.',
  'display_order': 102,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R01;R04',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM01_03',
  'dimension_code': 'MCM01',
  'construct': 'MCM',
  'prompt_ar': 'تحدد المنظمة بوضوح حدود ما ينبغي التواصل بشأنه بما يتفق مع أولوياتها الاستراتيجية.',
  'prompt_en': 'The organisation clearly defines boundaries for what should be communicated in line with its '
               'strategic priorities.',
  'display_order': 103,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R01;R04',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM01_04',
  'dimension_code': 'MCM01',
  'construct': 'MCM',
  'prompt_ar': 'يبدأ التخطيط الاتصالي بتحديد القرار أو الفعل المطلوب من الجمهور قبل اختيار القناة أو النشاط '
               'الاتصالي.',
  'prompt_en': 'Communication planning begins by defining the intended audience decision or action before selecting '
               'the channel or communication activity.',
  'display_order': 104,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R03;R05',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM02_01',
  'dimension_code': 'MCM02',
  'construct': 'MCM',
  'prompt_ar': 'تحدد المنظمة بصورة منهجية أصحاب المصلحة الرئيسيين واحتياجاتهم الاتصالية المختلفة.',
  'prompt_en': 'The organisation systematically identifies key stakeholders and their differing communication needs.',
  'display_order': 201,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R01;R05',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM02_02',
  'dimension_code': 'MCM02',
  'construct': 'MCM',
  'prompt_ar': 'تتكيف درجة التفصيل وطريقة عرض الرسالة مع مستوى معرفة صاحب المصلحة دون تغيير جوهر المعلومات.',
  'prompt_en': 'The level of detail and framing of a message are adapted to the stakeholder’s knowledge level '
               'without changing the underlying meaning.',
  'display_order': 202,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R01;R02',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM02_03',
  'dimension_code': 'MCM02',
  'construct': 'MCM',
  'prompt_ar': 'تراعي المنظمة سياق الجمهور ومستوى المخاطر المرتبط بالموضوع عند تصميم الاتصال.',
  'prompt_en': 'The organisation considers audience context and the level of risk associated with the issue when '
               'designing communication.',
  'display_order': 203,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R04;R08',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM02_04',
  'dimension_code': 'MCM02',
  'construct': 'MCM',
  'prompt_ar': 'توازن المنظمة بين احتياجات أصحاب المصلحة المختلفين عندما تتعارض أولوياتهم أو توقعاتهم.',
  'prompt_en': 'The organisation balances the needs of different stakeholders when their priorities or expectations '
               'conflict.',
  'display_order': 204,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R01;R04',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM03_01',
  'dimension_code': 'MCM03',
  'construct': 'MCM',
  'prompt_ar': 'يوجد مصدر رسمي معتمد وحديث للمعلومات الأساسية المتعلقة بالمنتجات والأسعار والسياسات.',
  'prompt_en': 'There is an official, approved, and current source for key product, pricing, and policy information.',
  'display_order': 301,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R06;R07',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM03_02',
  'dimension_code': 'MCM03',
  'construct': 'MCM',
  'prompt_ar': 'يمكن التحقق من مصدر الأدلة أو البيانات المستخدمة في الادعاءات والأرقام الاتصالية.',
  'prompt_en': 'The source of evidence or data used in communication claims and figures can be verified.',
  'display_order': 302,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R06;R07',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM03_03',
  'dimension_code': 'MCM03',
  'construct': 'MCM',
  'prompt_ar': 'عند تغيير معلومة أساسية توجد آلية تضمن تحديثها عبر القنوات والفرق والأنظمة ذات الصلة.',
  'prompt_en': 'When key information changes, a mechanism ensures that it is updated across relevant channels, '
               'teams, and systems.',
  'display_order': 303,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R01;R07',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM03_04',
  'dimension_code': 'MCM03',
  'construct': 'MCM',
  'prompt_ar': 'تخضع المعلومات الاتصالية الحساسة، بما فيها القيود والإفصاحات، لقواعد واضحة للمراجعة والتحديث.',
  'prompt_en': 'Sensitive communication information, including limitations and disclosures, is governed by clear '
               'review and update rules.',
  'display_order': 304,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R06;R07',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM04_01',
  'dimension_code': 'MCM04',
  'construct': 'MCM',
  'prompt_ar': 'يتم تنسيق الاتصال بين الوظائف التنظيمية ذات الصلة عند نقاط التداخل في رحلة العميل.',
  'prompt_en': 'Communication is coordinated across relevant organisational functions at customer journey '
               'intersections.',
  'display_order': 401,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R01;R04;R08',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM04_02',
  'dimension_code': 'MCM04',
  'construct': 'MCM',
  'prompt_ar': 'تحدد المنظمة نقاط الاتصال الحرجة في رحلة العميل وتوضح مسؤولية الاتصال عند كل منها.',
  'prompt_en': 'The organisation identifies critical customer journey touchpoints and clarifies communication '
               'ownership at each.',
  'display_order': 402,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R08',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM04_03',
  'dimension_code': 'MCM04',
  'construct': 'MCM',
  'prompt_ar': 'تتوافق الرسائل والإشعارات مع المرحلة أو الحالة الفعلية للعميل في الرحلة.',
  'prompt_en': 'Messages and notifications are aligned with the customer’s actual stage or state in the journey.',
  'display_order': 403,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R01;R08',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM04_04',
  'dimension_code': 'MCM04',
  'construct': 'MCM',
  'prompt_ar': 'تضع المنظمة معايير واضحة للاتصال الصادر عن الشركاء أو الأطراف الخارجية التي تمثلها.',
  'prompt_en': 'The organisation sets clear standards for communication produced by partners or external parties '
               'representing it.',
  'display_order': 404,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R01;R08',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM05_01',
  'dimension_code': 'MCM05',
  'construct': 'MCM',
  'prompt_ar': 'تعكس الرسائل التسويقية بدقة ما يمكن للمنتج أو الخدمة تقديمه فعليًا.',
  'prompt_en': 'Marketing messages accurately represent what the product or service can actually deliver.',
  'display_order': 501,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R08;R09;R26',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM05_02',
  'dimension_code': 'MCM05',
  'construct': 'MCM',
  'prompt_ar': 'توفر المنظمة معلومات واضحة تقلل تكوّن توقعات غير واقعية لدى العملاء.',
  'prompt_en': 'The organisation provides clear information that reduces the formation of unrealistic customer '
               'expectations.',
  'display_order': 502,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R09;R26',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM05_03',
  'dimension_code': 'MCM05',
  'construct': 'MCM',
  'prompt_ar': 'تُترجم الوعود التسويقية إلى معايير أو إجراءات تشغيلية واضحة خلال رحلة العميل.',
  'prompt_en': 'Marketing promises are translated into clear operational standards or processes across the customer '
               'journey.',
  'display_order': 503,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R08;R09',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM05_04',
  'dimension_code': 'MCM05',
  'construct': 'MCM',
  'prompt_ar': 'تراقب المنظمة بصورة منتظمة الفجوة بين ما تعد به اتصالاتها وما يختبره العميل فعليًا.',
  'prompt_en': 'The organisation regularly monitors the gap between what its communication promises and what '
               'customers actually experience.',
  'display_order': 504,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R08;R09;R26',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM06_01',
  'dimension_code': 'MCM06',
  'construct': 'MCM',
  'prompt_ar': 'تؤدي الأدلة المتاحة عن أداء الاتصال إلى تعديلات فعلية في الممارسات الاتصالية.',
  'prompt_en': 'Available evidence about communication performance leads to actual changes in communication '
               'practices.',
  'display_order': 601,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R05;R10;R17',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM06_02',
  'dimension_code': 'MCM06',
  'construct': 'MCM',
  'prompt_ar': 'تحلل المنظمة الأسئلة أو الشكاوى المتكررة للوصول إلى أسبابها الجذرية وتحويلها إلى تحسينات قابلة '
               'للتنفيذ.',
  'prompt_en': 'The organisation analyses recurring questions or complaints to identify root causes and convert them '
               'into actionable improvements.',
  'display_order': 602,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R10;R16',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM06_03',
  'dimension_code': 'MCM06',
  'construct': 'MCM',
  'prompt_ar': 'تركز المنظمة في تقييم الاتصال على مؤشرات مرتبطة بالفهم أو السلوك أو النتائج، وليس على حجم النشاط '
               'فقط.',
  'prompt_en': 'The organisation evaluates communication using indicators linked to understanding, behaviour, or '
               'outcomes rather than activity volume alone.',
  'display_order': 603,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R05;R17',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM06_04',
  'dimension_code': 'MCM06',
  'construct': 'MCM',
  'prompt_ar': 'تستخدم المنظمة الاتصال الاستباقي لتقديم المعلومات قبل أن تتحول الحاجة المتوقعة إلى سؤال أو مشكلة.',
  'prompt_en': 'The organisation uses proactive communication to provide information before a predictable need '
               'becomes a question or problem.',
  'display_order': 604,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R08;R10',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM07_01',
  'dimension_code': 'MCM07',
  'construct': 'MCM',
  'prompt_ar': 'المعرفة والإجراءات الاتصالية الأساسية موثقة بحيث لا تعتمد استمراريتها على أفراد محددين.',
  'prompt_en': 'Core communication knowledge and processes are documented so that continuity does not depend on '
               'specific individuals.',
  'display_order': 701,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R11;R12',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM07_02',
  'dimension_code': 'MCM07',
  'construct': 'MCM',
  'prompt_ar': 'توفر المنظمة معرفة إرشادية قابلة لإعادة الاستخدام تقلل الحاجة إلى الشرح اليدوي المتكرر.',
  'prompt_en': 'The organisation provides reusable guidance that reduces the need for repeated manual explanation.',
  'display_order': 702,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R12;R13',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM07_03',
  'dimension_code': 'MCM07',
  'construct': 'MCM',
  'prompt_ar': 'تخضع الأتمتة الاتصالية لقواعد حوكمة تضمن ملاءمة الرسالة للسياق.',
  'prompt_en': 'Communication automation is governed by rules that ensure messages remain appropriate to context.',
  'display_order': 703,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R11;R13',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'MCM07_04',
  'dimension_code': 'MCM07',
  'construct': 'MCM',
  'prompt_ar': 'تحافظ المنظمة على جودة واتساق الاتصال مع نمو عدد العملاء أو المنتجات أو القنوات أو الشركاء.',
  'prompt_en': 'The organisation maintains communication quality and consistency as the number of customers, '
               'products, channels, or partners grows.',
  'display_order': 704,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'MCM_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R03;R11',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'SMCE01_01',
  'dimension_code': 'SMCE01',
  'construct': 'SMCE',
  'prompt_ar': 'تستجيب المنظمة للاستفسارات والمشكلات عبر وسائل التواصل خلال وقت يتناسب مع درجة أهميتها.',
  'prompt_en': 'The organisation responds to social media inquiries and issues within a timeframe appropriate to '
               'their importance.',
  'display_order': 1101,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'SMCE_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R15',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'SMCE01_02',
  'dimension_code': 'SMCE01',
  'construct': 'SMCE',
  'prompt_ar': 'تكون الاستجابة الأولية عبر وسائل التواصل دقيقة وملائمة للموقف، وليست مجرد استجابة سريعة.',
  'prompt_en': 'The initial social media response is accurate and appropriate to the situation rather than merely '
               'fast.',
  'display_order': 1102,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'SMCE_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R15;R16',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'SMCE01_03',
  'dimension_code': 'SMCE01',
  'construct': 'SMCE',
  'prompt_ar': 'تتم معالجة مشكلات العملاء عبر وسائل التواصل حتى الوصول إلى حل أو تصعيد مناسب.',
  'prompt_en': 'Customer issues raised through social media are handled through to resolution or appropriate '
               'escalation.',
  'display_order': 1103,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'SMCE_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R15;R16',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'SMCE02_01',
  'dimension_code': 'SMCE02',
  'construct': 'SMCE',
  'prompt_ar': 'تشير البيانات المتاحة للمنظمة إلى أن الجمهور يفهم المعنى المقصود من رسائلها على وسائل التواصل بصورة '
               'صحيحة.',
  'prompt_en': 'Available organisational evidence indicates that audiences correctly understand the intended meaning '
               'of its social media messages.',
  'display_order': 1201,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'SMCE_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R02;R04',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'SMCE02_02',
  'dimension_code': 'SMCE02',
  'construct': 'SMCE',
  'prompt_ar': 'تعكس الأسئلة والتفاعلات الناتجة عن المحتوى فهمًا ذا صلة أكثر من كونها ناتجة عن الالتباس.',
  'prompt_en': 'Questions and interactions generated by content tend to reflect relevant understanding rather than '
               'confusion.',
  'display_order': 1202,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'SMCE_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R02;R04',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'SMCE02_03',
  'dimension_code': 'SMCE02',
  'construct': 'SMCE',
  'prompt_ar': 'تنتج اتصالات المنظمة عبر وسائل التواصل حوارًا ذا صلة بالموضوع أو القرار المقصود.',
  'prompt_en': 'The organisation’s social media communication generates dialogue relevant to the intended topic or '
               'decision.',
  'display_order': 1203,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'SMCE_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R02;R04',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'SMCE03_01',
  'dimension_code': 'SMCE03',
  'construct': 'SMCE',
  'prompt_ar': 'ينقل التواصل عبر وسائل التواصل الجمهور المناسب نحو الخطوة التالية المقصودة.',
  'prompt_en': 'Social media communication moves the appropriate audience toward the intended next action.',
  'display_order': 1301,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'SMCE_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R03;R17',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'SMCE03_02',
  'dimension_code': 'SMCE03',
  'construct': 'SMCE',
  'prompt_ar': 'تشير البيانات المتاحة إلى أن الجمهور يستطيع إكمال الخطوات المطلوبة دون تعثر ناتج عن غموض الاتصال.',
  'prompt_en': 'Available evidence indicates that audiences can complete intended steps without '
               'communication-related confusion causing avoidable drop-off.',
  'display_order': 1302,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'SMCE_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R08;R17',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'SMCE03_03',
  'dimension_code': 'SMCE03',
  'construct': 'SMCE',
  'prompt_ar': 'تنتج الأنشطة الاتصالية استفسارات أو إجراءات ذات صلة ومؤهلة بدلًا من مجرد زيادة الحجم.',
  'prompt_en': 'Communication activities generate relevant and qualified inquiries or actions rather than merely '
               'increasing volume.',
  'display_order': 1303,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'SMCE_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R14;R17',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'SMCE04_01',
  'dimension_code': 'SMCE04',
  'construct': 'SMCE',
  'prompt_ar': 'تكون طلبات التوضيح المتكررة الناتجة عن غموض أو نقص المعلومات الاتصالية محدودة.',
  'prompt_en': 'Repeated clarification requests caused by unclear or incomplete communication are limited.',
  'display_order': 1401,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'SMCE_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R08;R26',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'SMCE04_02',
  'dimension_code': 'SMCE04',
  'construct': 'SMCE',
  'prompt_ar': 'تكون الحاجة إلى إعادة العمل الناتجة عن سوء فهم المعلومات الاتصالية محدودة.',
  'prompt_en': 'The need for rework caused by misunderstanding communication information is limited.',
  'display_order': 1402,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'SMCE_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R16;R26',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'SMCE04_03',
  'dimension_code': 'SMCE04',
  'construct': 'SMCE',
  'prompt_ar': 'تكون الشكاوى الناتجة عن اختلاف التوقعات أو تضارب المعلومات بين القنوات محدودة.',
  'prompt_en': 'Complaints caused by expectation mismatch or inconsistent information across channels are limited.',
  'display_order': 1403,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'SMCE_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R09;R26',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'SMCE05_01',
  'dimension_code': 'SMCE05',
  'construct': 'SMCE',
  'prompt_ar': 'تتناسب الموارد المستخدمة في التواصل عبر وسائل التواصل مع النتائج ذات المعنى التي تحققها المنظمة.',
  'prompt_en': 'Resources used for social media communication are proportionate to the meaningful outcomes achieved.',
  'display_order': 1501,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'SMCE_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R14;R17',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'SMCE05_02',
  'dimension_code': 'SMCE05',
  'construct': 'SMCE',
  'prompt_ar': 'تتحسن كفاءة الوقت أو التكلفة اللازمة لتحقيق نتيجة اتصالية ذات معنى بمرور الوقت.',
  'prompt_en': 'The time or cost efficiency of achieving a meaningful communication outcome improves over time.',
  'display_order': 1502,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'SMCE_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R17',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'SMCE05_03',
  'dimension_code': 'SMCE05',
  'construct': 'SMCE',
  'prompt_ar': 'تحقق المنظمة أهدافها الاتصالية دون زيادة غير متناسبة في الموارد المستخدمة مع نمو حجم النشاط.',
  'prompt_en': 'The organisation achieves its communication goals without disproportionate increases in resource use '
               'as activity volume grows.',
  'display_order': 1503,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'SMCE_TOTAL',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R14;R17',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'OUT01_01',
  'dimension_code': 'OUT01',
  'construct': 'OUTCOME',
  'prompt_ar': 'تشير الأدلة المتاحة إلى أن أصحاب المصلحة يعتبرون معلومات المنظمة موثوقة.',
  'prompt_en': 'Available evidence indicates that stakeholders regard the organisation’s information as reliable.',
  'display_order': 2101,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'OPTIONAL_OUTCOME',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R18',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'OUT01_02',
  'dimension_code': 'OUT01',
  'construct': 'OUTCOME',
  'prompt_ar': 'تشير الأدلة المتاحة إلى أن أصحاب المصلحة يعتبرون اتصالات المنظمة ذات مصداقية.',
  'prompt_en': 'Available evidence indicates that stakeholders regard the organisation’s communication as credible.',
  'display_order': 2102,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'OPTIONAL_OUTCOME',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R18',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'OUT01_03',
  'dimension_code': 'OUT01',
  'construct': 'OUTCOME',
  'prompt_ar': 'تشير الأدلة المتاحة إلى أن أصحاب المصلحة يمكنهم الاعتماد على المنظمة في الوفاء بما تتواصل بشأنه.',
  'prompt_en': 'Available evidence indicates that stakeholders can rely on the organisation to act consistently with '
               'what it communicates.',
  'display_order': 2103,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'OPTIONAL_OUTCOME',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R18;R09',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'OUT02_01',
  'dimension_code': 'OUT02',
  'construct': 'OUTCOME',
  'prompt_ar': 'تشير بيانات العملاء إلى مستوى مرتفع من الرضا العام عن تجربتهم مع المنظمة.',
  'prompt_en': 'Customer evidence indicates a high level of overall satisfaction with their experience with the '
               'organisation.',
  'display_order': 2201,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'OPTIONAL_OUTCOME',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R19',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'OUT02_02',
  'dimension_code': 'OUT02',
  'construct': 'OUTCOME',
  'prompt_ar': 'تشير بيانات العملاء إلى أن التجربة مع المنظمة تلبي توقعاتهم بدرجة جيدة.',
  'prompt_en': 'Customer evidence indicates that the experience with the organisation meets customer expectations '
               'well.',
  'display_order': 2202,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'OPTIONAL_OUTCOME',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R19',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'OUT02_03',
  'dimension_code': 'OUT02',
  'construct': 'OUTCOME',
  'prompt_ar': 'تشير بيانات العملاء إلى أن التجربة الكلية تقترب من المستوى الذي يتوقعونه من مقدم خدمة ممتاز.',
  'prompt_en': 'Customer evidence indicates that the overall experience is close to the level customers expect from '
               'an excellent provider.',
  'display_order': 2203,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'OPTIONAL_OUTCOME',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R19',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'OUT03_01',
  'dimension_code': 'OUT03',
  'construct': 'OUTCOME',
  'prompt_ar': 'تشير الأدلة المتاحة إلى أن الجمهور المستهدف يتعرف على العلامة التجارية ويتذكرها بسهولة.',
  'prompt_en': 'Available evidence indicates that the target audience readily recognises and recalls the brand.',
  'display_order': 2301,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'OPTIONAL_OUTCOME',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R20',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'OUT03_02',
  'dimension_code': 'OUT03',
  'construct': 'OUTCOME',
  'prompt_ar': 'تشير الأدلة المتاحة إلى أن العلامة التجارية تُدرك على أنها متميزة عن البدائل الرئيسية.',
  'prompt_en': 'Available evidence indicates that the brand is perceived as distinct from major alternatives.',
  'display_order': 2302,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'OPTIONAL_OUTCOME',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R20',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'OUT03_03',
  'dimension_code': 'OUT03',
  'construct': 'OUTCOME',
  'prompt_ar': 'تشير الأدلة المتاحة إلى وجود تفضيل للعلامة عند توفر بدائل متقاربة.',
  'prompt_en': 'Available evidence indicates preference for the brand when comparable alternatives are available.',
  'display_order': 2303,
  'response_type': 'LIKERT_EXTENT',
  'scale_code': 'LIKERT_5_EXTENT',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'OPTIONAL_OUTCOME',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R20',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'OUT04_01',
  'dimension_code': 'OUT04',
  'construct': 'OUTCOME',
  'prompt_ar': 'مقارنة بالمنافسين الرئيسيين، كان أداء المنظمة في نمو المبيعات أو الإيرادات أفضل خلال الفترة '
               'المرجعية.',
  'prompt_en': 'Compared with major competitors, the organisation performed better in sales or revenue growth during '
               'the reference period.',
  'display_order': 2401,
  'response_type': 'LIKERT_RELATIVE',
  'scale_code': 'RELATIVE_5_COMPETITOR',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'OPTIONAL_OUTCOME',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R14;R21',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'OUT04_02',
  'dimension_code': 'OUT04',
  'construct': 'OUTCOME',
  'prompt_ar': 'مقارنة بالمنافسين الرئيسيين، كان الأداء المالي العام للمنظمة أفضل خلال الفترة المرجعية.',
  'prompt_en': 'Compared with major competitors, the organisation’s overall financial performance was better during '
               'the reference period.',
  'display_order': 2402,
  'response_type': 'LIKERT_RELATIVE',
  'scale_code': 'RELATIVE_5_COMPETITOR',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'OPTIONAL_OUTCOME',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R14;R21',
  'item_status': 'EXPERT_REVIEW'},
 {'code': 'OUT04_03',
  'dimension_code': 'OUT04',
  'construct': 'OUTCOME',
  'prompt_ar': 'مقارنة بالمنافسين الرئيسيين، كان أداء المنظمة في اكتساب العملاء أو الاحتفاظ بهم أفضل خلال الفترة '
               'المرجعية.',
  'prompt_en': 'Compared with major competitors, the organisation performed better in customer acquisition or '
               'retention during the reference period.',
  'display_order': 2403,
  'response_type': 'LIKERT_RELATIVE',
  'scale_code': 'RELATIVE_5_COMPETITOR',
  'required': True,
  'reverse_coded': False,
  'weight': 1.0,
  'include_in_score': True,
  'score_group': 'OPTIONAL_OUTCOME',
  'source_type': 'DEVELOPED_FROM_LITERATURE',
  'source_reference': 'R14;R21',
  'item_status': 'EXPERT_REVIEW'}]

PROFILE_FIELDS = [{'code': 'CTX_FIRM_SIZE',
  'construct': 'CONTEXT',
  'label_ar': 'حجم المنشأة',
  'label_en': 'Firm size',
  'response_type': 'CATEGORICAL',
  'include_in_score': False,
  'source_reference': 'Firm size / control variable'},
 {'code': 'CTX_EMPLOYEE_COUNT',
  'construct': 'CONTEXT',
  'label_ar': 'عدد الموظفين',
  'label_en': 'Number of employees',
  'response_type': 'NUMERIC',
  'include_in_score': False,
  'source_reference': 'Firm size / control variable'},
 {'code': 'CTX_FIRM_AGE',
  'construct': 'CONTEXT',
  'label_ar': 'عمر المنشأة بالسنوات',
  'label_en': 'Firm age in years',
  'response_type': 'NUMERIC',
  'include_in_score': False,
  'source_reference': 'Firm age / control variable'},
 {'code': 'CTX_SECTOR',
  'construct': 'CONTEXT',
  'label_ar': 'قطاع المنشأة',
  'label_en': 'Firm sector',
  'response_type': 'CATEGORICAL',
  'include_in_score': False,
  'source_reference': 'Sector / control variable'},
 {'code': 'CTX_BUSINESS_MODEL',
  'construct': 'CONTEXT',
  'label_ar': 'نموذج الأعمال',
  'label_en': 'Business model',
  'response_type': 'CATEGORICAL',
  'include_in_score': False,
  'source_reference': 'Context variable'},
 {'code': 'CTX_REGION',
  'construct': 'CONTEXT',
  'label_ar': 'المنطقة الرئيسية للنشاط',
  'label_en': 'Primary operating region',
  'response_type': 'CATEGORICAL',
  'include_in_score': False,
  'source_reference': 'Context variable'},
 {'code': 'CTX_SOCIAL_PLATFORM_COUNT',
  'construct': 'CONTEXT',
  'label_ar': 'عدد منصات التواصل الاجتماعي المستخدمة بانتظام',
  'label_en': 'Number of social media platforms used regularly',
  'response_type': 'NUMERIC',
  'include_in_score': False,
  'source_reference': 'Social platform count / control variable'},
 {'code': 'CTX_SOCIAL_TEAM_SIZE',
  'construct': 'CONTEXT',
  'label_ar': 'عدد العاملين المسؤولين بصورة مباشرة عن التواصل عبر وسائل التواصل',
  'label_en': 'Number of staff directly responsible for social media communication',
  'response_type': 'NUMERIC',
  'include_in_score': False,
  'source_reference': 'Social team size / control variable'},
 {'code': 'CTX_REGULATED',
  'construct': 'CONTEXT',
  'label_ar': 'هل تعمل المنشأة في قطاع منظم رقابيًا؟',
  'label_en': 'Does the firm operate in a regulated sector?',
  'response_type': 'BOOLEAN',
  'include_in_score': False,
  'source_reference': 'Context variable'}]

MATURITY_LEVELS = [{'level_order': 1,
  'code': 'REACTIVE_AD_HOC',
  'label_ar': 'عشوائي',
  'label_en': 'Reactive / Ad hoc',
  'min_score': 0.0,
  'max_score': 20.0,
  'threshold_status': 'PROVISIONAL_LABEL_ONLY',
  'source_reference': 'Analytical pretest developmental logic'},
 {'level_order': 2,
  'code': 'RESPONSIVE_EMERGING',
  'label_ar': 'ناشئ',
  'label_en': 'Responsive / Emerging',
  'min_score': 20.0,
  'max_score': 40.0,
  'threshold_status': 'PROVISIONAL_LABEL_ONLY',
  'source_reference': 'Analytical pretest developmental logic'},
 {'level_order': 3,
  'code': 'MANAGED_INTEGRATED',
  'label_ar': 'متكامل',
  'label_en': 'Managed & Integrated',
  'min_score': 40.0,
  'max_score': 60.0,
  'threshold_status': 'PROVISIONAL_LABEL_ONLY',
  'source_reference': 'Analytical pretest developmental logic'},
 {'level_order': 4,
  'code': 'PROACTIVE_ADAPTIVE',
  'label_ar': 'استباقي ومتكيف',
  'label_en': 'Proactive & Adaptive',
  'min_score': 60.0,
  'max_score': 80.0,
  'threshold_status': 'PROVISIONAL_LABEL_ONLY',
  'source_reference': 'Analytical pretest developmental logic'},
 {'level_order': 5,
  'code': 'INSTITUTIONALISED_INTELLIGENT',
  'label_ar': 'مؤسسي وذكي',
  'label_en': 'Institutionalised & Intelligent',
  'min_score': 80.0,
  'max_score': 100.01,
  'threshold_status': 'PROVISIONAL_LABEL_ONLY',
  'source_reference': 'Analytical pretest developmental logic'}]

