from __future__ import annotations

import re
from collections.abc import Iterator, Mapping
from typing import Any
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit


IDENTITY_TABLES = {
    "organizations",
    "users",
    "consents",
    "instruments",
    "instrument_versions",
    "dimensions",
    "scales",
    "scale_values",
    "items",
    "maturity_levels",
    "assessments",
    "instrument_profile_fields",
    "participants",
    "responses",
    "score_runs",
    "response_item_scores",
    "diagnostic_rules",
    "diagnostic_results",
    "recommendations",
    "roadmap_items",
    "invitations",
    "notifications",
    "reports",
    "research_exports",
    "data_quality_flags",
    "audit_logs",
}


class HybridRow(Mapping):
    """A psycopg row with sqlite3.Row-compatible name and index access."""

    __slots__ = ("_names", "_values", "_positions")

    def __init__(self, names: tuple[str, ...], values: tuple[Any, ...]):
        self._names = names
        self._values = values
        self._positions = {name: index for index, name in enumerate(names)}

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._values[key]
        return self._values[self._positions[key]]

    def __iter__(self) -> Iterator[str]:
        return iter(self._names)

    def __len__(self) -> int:
        return len(self._names)

    def keys(self):
        return self._names


def hybrid_row_factory(cursor):
    # DDL and other statements without a result set report `description` as
    # None. psycopg still builds a row maker, so tolerate the empty case.
    description = cursor.description
    names = tuple(column.name for column in description) if description else ()

    def make_row(values):
        return HybridRow(names, tuple(values))

    return make_row


def _qmark_to_format(sql: str) -> str:
    """Convert DB-API qmarks outside SQL strings to psycopg placeholders."""
    output: list[str] = []
    quote: str | None = None
    index = 0
    while index < len(sql):
        char = sql[index]
        if quote:
            output.append(char)
            if char == quote:
                if index + 1 < len(sql) and sql[index + 1] == quote:
                    output.append(sql[index + 1])
                    index += 1
                else:
                    quote = None
        elif char in {"'", '"'}:
            quote = char
            output.append(char)
        elif char == "?":
            output.append("%s")
        else:
            output.append(char)
        index += 1
    return "".join(output)


def postgres_sql(sql: str) -> tuple[str, bool]:
    """Translate the small SQLite SQL subset used by the application."""
    normalized = sql.strip()
    if re.match(r"^BEGIN\s+IMMEDIATE\s*;?$", normalized, re.IGNORECASE):
        return "", False

    replace_scores = re.match(
        r"^INSERT\s+OR\s+REPLACE\s+INTO\s+scores\s+VALUES\s*\(",
        normalized,
        re.IGNORECASE,
    )
    if replace_scores:
        normalized = re.sub(
            r"^INSERT\s+OR\s+REPLACE\s+INTO\s+scores",
            "INSERT INTO scores",
            normalized,
            flags=re.IGNORECASE,
        )
        normalized += (
            " ON CONFLICT (assessment_id,construct,dimension_code) "
            "DO UPDATE SET score=EXCLUDED.score"
        )

    ignore_insert = bool(
        re.match(r"^INSERT\s+OR\s+IGNORE\s+INTO\s+", normalized, re.IGNORECASE)
    )
    if ignore_insert:
        normalized = re.sub(
            r"^INSERT\s+OR\s+IGNORE\s+INTO\s+",
            "INSERT INTO ",
            normalized,
            flags=re.IGNORECASE,
        )
        if " ON CONFLICT " not in normalized.upper():
            normalized += " ON CONFLICT DO NOTHING"

    insert = re.match(r"^INSERT\s+INTO\s+([A-Za-z_][A-Za-z0-9_]*)\b", normalized, re.IGNORECASE)
    table = insert.group(1).lower() if insert else None
    single_values_insert = bool(insert and re.search(r"\bVALUES\s*\(", normalized, re.IGNORECASE))
    should_return_id = bool(
        table in IDENTITY_TABLES
        and single_values_insert
        and " RETURNING " not in normalized.upper()
    )
    if should_return_id:
        normalized += " RETURNING id"

    return _qmark_to_format(normalized), should_return_id


def postgres_schema(sqlite_schema: str) -> str:
    """Create a PostgreSQL-compatible schema that preserves application types."""
    schema = sqlite_schema.replace(
        "INTEGER PRIMARY KEY AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    )
    parts = re.split(r"('(?:''|[^'])*'|\"(?:\"\"|[^\"])*\")", schema)
    for index in range(0, len(parts), 2):
        parts[index] = re.sub(r"\bINTEGER\b", "BIGINT", parts[index])
        parts[index] = re.sub(r"\bREAL\b", "DOUBLE PRECISION", parts[index])
    schema = "".join(parts)
    return schema.replace(" BLOB", " BYTEA")


def schema_table_names(schema: str) -> list[str]:
    return re.findall(
        r"CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+([A-Za-z_][A-Za-z0-9_]*)",
        schema,
        flags=re.IGNORECASE,
    )


# Supabase hands out pooler URLs carrying a vendor marker (`?supa=base-pooler.x`)
# that libpq rejects outright with `invalid URI query parameter: "supa"`. A URL
# copied verbatim from the provider console is a correct credential, so drop the
# vendor parameters instead of failing the connection.
VENDOR_QUERY_PARAMS = frozenset({"supa"})


def normalize_database_url(database_url: str) -> str:
    """Remove provider-specific query parameters libpq refuses to parse."""
    parts = urlsplit(database_url)
    if not parts.query:
        return database_url
    kept = [
        (key, value)
        for key, value in parse_qsl(parts.query, keep_blank_values=True)
        if key.lower() not in VENDOR_QUERY_PARAMS
    ]
    return urlunsplit(parts._replace(query=urlencode(kept)))


def connection_security_options(database_url: str) -> dict[str, str]:
    """Require encrypted PostgreSQL transport and preserve stricter URL modes."""
    query = {
        key.lower(): value.lower()
        for key, value in parse_qsl(urlsplit(database_url).query)
    }
    sslmode = query.get("sslmode")
    if not sslmode:
        return {"sslmode": "require"}
    if sslmode not in {"require", "verify-ca", "verify-full"}:
        raise ValueError("PostgreSQL sslmode must be require, verify-ca, or verify-full")
    return {}


class CursorAdapter:
    def __init__(self, cursor=None, lastrowid=None):
        self._cursor = cursor
        self.lastrowid = lastrowid

    @property
    def rowcount(self):
        return self._cursor.rowcount if self._cursor is not None else 0

    def fetchone(self):
        return self._cursor.fetchone() if self._cursor is not None else None

    def fetchall(self):
        return self._cursor.fetchall() if self._cursor is not None else []

    def __iter__(self):
        return iter(self._cursor) if self._cursor is not None else iter(())


class PostgresConnection:
    """Minimal sqlite-like facade over a short-lived psycopg connection."""

    backend = "postgresql"

    def __init__(self, connection):
        self._connection = connection

    def execute(self, sql: str, params=()):
        translated, returns_id = postgres_sql(sql)
        if not translated:
            return CursorAdapter()
        cursor = self._connection.cursor()
        cursor.execute(translated, tuple(params or ()))
        lastrowid = None
        if returns_id:
            row = cursor.fetchone()
            lastrowid = row[0] if row is not None else None
        return CursorAdapter(cursor, lastrowid)

    def executescript(self, script: str):
        cursor = self._connection.cursor()
        for statement in script.split(";"):
            statement = statement.strip()
            if statement:
                cursor.execute(statement)
        return CursorAdapter(cursor)

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()


def connect_postgres(database_url: str, *, application_name: str = "mcm-platform"):
    try:
        import psycopg
    except ImportError as exc:  # pragma: no cover - exercised in the Vercel build
        raise RuntimeError(
            "PostgreSQL storage requires the psycopg[binary] dependency."
        ) from exc

    database_url = normalize_database_url(database_url)
    connection = psycopg.connect(
        database_url,
        connect_timeout=10,
        application_name=application_name,
        prepare_threshold=None,
        row_factory=hybrid_row_factory,
        **connection_security_options(database_url),
    )
    return PostgresConnection(connection)
