-- Supabase/PostgreSQL durable schema for the MCM platform.
-- Auditable schema snapshot only; do not apply it separately.
-- Apply schema + seed atomically with a direct/session connection: python -m mcm.migrate
BEGIN;

CREATE TABLE IF NOT EXISTS schema_migrations (
  version BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  applied_at BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS organizations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  locale TEXT NOT NULL DEFAULT 'ar',
  sector TEXT,
  subsector TEXT,
  size TEXT,
  country TEXT,
  region TEXT,
  data_origin TEXT NOT NULL DEFAULT 'REAL',
  created_at BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  job_title TEXT,
  phone TEXT,
  preferred_language TEXT NOT NULL DEFAULT 'ar',
  verified BIGINT NOT NULL DEFAULT 1,
  is_active BIGINT NOT NULL DEFAULT 1,
  created_at BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS memberships (
  user_id BIGINT NOT NULL,
  organization_id BIGINT NOT NULL,
  role TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY(user_id, organization_id),
  FOREIGN KEY(user_id) REFERENCES users(id),
  FOREIGN KEY(organization_id) REFERENCES organizations(id)
);
CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  active_org_id BIGINT,
  expires_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL DEFAULT 0,
  last_seen_at BIGINT NOT NULL DEFAULT 0,
  FOREIGN KEY(user_id) REFERENCES users(id),
  FOREIGN KEY(active_org_id) REFERENCES organizations(id)
);
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  token_hash TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  expires_at BIGINT NOT NULL,
  used_at BIGINT,
  FOREIGN KEY(user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS consents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  participant_id BIGINT,
  consent_type TEXT NOT NULL,
  consent_version TEXT NOT NULL,
  accepted BIGINT NOT NULL,
  accepted_at BIGINT NOT NULL,
  CHECK ((user_id IS NOT NULL AND participant_id IS NULL) OR (user_id IS NULL AND participant_id IS NOT NULL)),
  UNIQUE(user_id, participant_id, consent_type, consent_version)
);
CREATE TABLE IF NOT EXISTS company_profiles (
  organization_id BIGINT PRIMARY KEY,
  website TEXT,
  business_model TEXT,
  employee_count TEXT,
  annual_revenue_band TEXT,
  communication_team_size TEXT,
  channels_json TEXT NOT NULL DEFAULT '[]',
  crm_system TEXT,
  analytics_system TEXT,
  research_consent BIGINT NOT NULL DEFAULT 0,
  completion BIGINT NOT NULL DEFAULT 0,
  updated_at BIGINT NOT NULL DEFAULT 0,
  FOREIGN KEY(organization_id) REFERENCES organizations(id)
);
CREATE TABLE IF NOT EXISTS organization_profiles (
  organization_id BIGINT PRIMARY KEY,
  industry TEXT,
  website TEXT,
  completion BIGINT NOT NULL DEFAULT 0,
  FOREIGN KEY(organization_id) REFERENCES organizations(id)
);
CREATE TABLE IF NOT EXISTS instruments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  created_at BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS instrument_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instrument_id BIGINT NOT NULL,
  version TEXT NOT NULL,
  status TEXT NOT NULL,
  product_status TEXT NOT NULL DEFAULT 'DRAFT',
  scientific_status TEXT NOT NULL DEFAULT 'EVIDENCE_INFORMED',
  scientific_status_changed_at BIGINT,
  scientific_status_changed_by BIGINT,
  notes TEXT,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_by BIGINT,
  created_at BIGINT NOT NULL DEFAULT 0,
  published_at BIGINT,
  archived_at BIGINT,
  UNIQUE(instrument_id, version),
  FOREIGN KEY(instrument_id) REFERENCES instruments(id)
);
CREATE TABLE IF NOT EXISTS dimensions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id BIGINT,
  code TEXT NOT NULL,
  construct TEXT NOT NULL,
  name TEXT NOT NULL,
  name_en TEXT,
  weight DOUBLE PRECISION NOT NULL DEFAULT 1,
  source_type TEXT,
  source_reference TEXT,
  sort_order BIGINT NOT NULL DEFAULT 0,
  content_json TEXT,
  UNIQUE(version_id, code),
  FOREIGN KEY(version_id) REFERENCES instrument_versions(id)
);
CREATE TABLE IF NOT EXISTS scales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id BIGINT NOT NULL,
  code TEXT NOT NULL,
  response_type TEXT NOT NULL DEFAULT 'LIKERT',
  min_value DOUBLE PRECISION,
  max_value DOUBLE PRECISION,
  UNIQUE(version_id, code),
  FOREIGN KEY(version_id) REFERENCES instrument_versions(id)
);
CREATE TABLE IF NOT EXISTS scale_values (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scale_id BIGINT NOT NULL,
  value DOUBLE PRECISION,
  label_ar TEXT,
  label_en TEXT,
  missing_type TEXT,
  FOREIGN KEY(scale_id) REFERENCES scales(id)
);
CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id BIGINT NOT NULL,
  code TEXT NOT NULL,
  construct TEXT NOT NULL,
  dimension_code TEXT NOT NULL,
  prompt_ar TEXT NOT NULL,
  prompt_en TEXT,
  source TEXT,
  lifecycle_status TEXT NOT NULL DEFAULT 'PILOT',
  reverse_coded BIGINT NOT NULL DEFAULT 0,
  required BIGINT NOT NULL DEFAULT 1,
  weight DOUBLE PRECISION NOT NULL DEFAULT 1,
  response_type TEXT NOT NULL DEFAULT 'LIKERT',
  scale_code TEXT,
  include_in_score BIGINT NOT NULL DEFAULT 1,
  score_group TEXT,
  source_type TEXT,
  source_reference TEXT,
  min_value DOUBLE PRECISION DEFAULT 1,
  max_value DOUBLE PRECISION DEFAULT 5,
  sort_order BIGINT NOT NULL DEFAULT 0,
  UNIQUE(version_id, code),
  FOREIGN KEY(version_id) REFERENCES instrument_versions(id)
);
CREATE TABLE IF NOT EXISTS maturity_levels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id BIGINT NOT NULL,
  code TEXT NOT NULL,
  label_ar TEXT NOT NULL,
  label_en TEXT NOT NULL,
  min_score DOUBLE PRECISION NOT NULL,
  max_score DOUBLE PRECISION NOT NULL,
  threshold_status TEXT NOT NULL DEFAULT 'PROVISIONAL_LABEL_ONLY',
  source_reference TEXT,
  level_order BIGINT NOT NULL,
  content_json TEXT,
  UNIQUE(version_id, code),
  FOREIGN KEY(version_id) REFERENCES instrument_versions(id)
);
CREATE TABLE IF NOT EXISTS assessments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL,
  version_id BIGINT NOT NULL,
  created_by BIGINT NOT NULL,
  assessment_type TEXT NOT NULL DEFAULT 'FULL',
  status TEXT NOT NULL,
  data_origin TEXT NOT NULL DEFAULT 'REAL',
  parent_assessment_id BIGINT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL DEFAULT 0,
  submitted_at BIGINT,
  completed_at BIGINT,
  FOREIGN KEY(organization_id) REFERENCES organizations(id),
  FOREIGN KEY(version_id) REFERENCES instrument_versions(id),
  FOREIGN KEY(parent_assessment_id) REFERENCES assessments(id)
);
CREATE TABLE IF NOT EXISTS assessment_context (
  assessment_id BIGINT PRIMARY KEY,
  sector TEXT NOT NULL,
  firm_size TEXT NOT NULL,
  employee_count BIGINT,
  firm_age_years BIGINT NOT NULL,
  business_model TEXT,
  region TEXT NOT NULL,
  social_platform_count BIGINT NOT NULL,
  social_team_size BIGINT,
  regulated BIGINT,
  respondent_role TEXT NOT NULL,
  leadership_support DOUBLE PRECISION,
  human_competencies DOUBLE PRECISION,
  technology_infrastructure DOUBLE PRECISION,
  data_readiness DOUBLE PRECISION,
  created_at BIGINT NOT NULL,
  FOREIGN KEY(assessment_id) REFERENCES assessments(id)
);
CREATE TABLE IF NOT EXISTS instrument_profile_fields (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id BIGINT NOT NULL,
  code TEXT NOT NULL,
  construct TEXT NOT NULL DEFAULT 'CONTEXT',
  label_ar TEXT NOT NULL,
  label_en TEXT,
  response_type TEXT NOT NULL,
  include_in_score BIGINT NOT NULL DEFAULT 0,
  source_reference TEXT,
  sort_order BIGINT NOT NULL DEFAULT 0,
  UNIQUE(version_id, code),
  FOREIGN KEY(version_id) REFERENCES instrument_versions(id)
);
CREATE TABLE IF NOT EXISTS participants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  research_id TEXT UNIQUE,
  organization_id BIGINT NOT NULL,
  user_id BIGINT,
  full_name TEXT,
  email TEXT,
  job_title TEXT,
  department TEXT,
  created_at BIGINT NOT NULL,
  FOREIGN KEY(organization_id) REFERENCES organizations(id),
  FOREIGN KEY(user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS assessment_participants (
  assessment_id BIGINT NOT NULL,
  participant_id BIGINT NOT NULL,
  assessment_role TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'INVITED',
  PRIMARY KEY(assessment_id, participant_id),
  FOREIGN KEY(assessment_id) REFERENCES assessments(id),
  FOREIGN KEY(participant_id) REFERENCES participants(id)
);
CREATE TABLE IF NOT EXISTS responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id BIGINT NOT NULL,
  participant_id BIGINT NOT NULL DEFAULT 0,
  item_id BIGINT NOT NULL,
  numeric_value DOUBLE PRECISION,
  text_value TEXT,
  missing_type TEXT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  UNIQUE(assessment_id, participant_id, item_id),
  FOREIGN KEY(assessment_id) REFERENCES assessments(id),
  FOREIGN KEY(item_id) REFERENCES items(id)
);
CREATE TABLE IF NOT EXISTS answers (
  assessment_id BIGINT,
  item_id BIGINT,
  value DOUBLE PRECISION NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY(assessment_id, item_id),
  FOREIGN KEY(assessment_id) REFERENCES assessments(id),
  FOREIGN KEY(item_id) REFERENCES items(id)
);
CREATE TABLE IF NOT EXISTS assessment_scores (
  assessment_id BIGINT NOT NULL,
  construct TEXT NOT NULL,
  total_score DOUBLE PRECISION NOT NULL,
  maturity_level_id BIGINT,
  answered_count BIGINT NOT NULL,
  method_version TEXT NOT NULL,
  calculated_at BIGINT NOT NULL,
  PRIMARY KEY(assessment_id, construct),
  FOREIGN KEY(assessment_id) REFERENCES assessments(id),
  FOREIGN KEY(maturity_level_id) REFERENCES maturity_levels(id)
);
CREATE TABLE IF NOT EXISTS score_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id BIGINT NOT NULL,
  run_number BIGINT NOT NULL,
  instrument_version_id BIGINT NOT NULL,
  scoring_version TEXT NOT NULL,
  configuration_json TEXT NOT NULL,
  input_hash TEXT NOT NULL,
  output_hash TEXT,
  is_current BIGINT NOT NULL DEFAULT 1,
  created_at BIGINT NOT NULL,
  UNIQUE(assessment_id, run_number),
  FOREIGN KEY(assessment_id) REFERENCES assessments(id),
  FOREIGN KEY(instrument_version_id) REFERENCES instrument_versions(id)
);
CREATE TABLE IF NOT EXISTS response_item_scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  score_run_id BIGINT NOT NULL,
  item_id BIGINT NOT NULL,
  raw_value DOUBLE PRECISION,
  effective_value DOUBLE PRECISION,
  normalized_score DOUBLE PRECISION,
  reverse_coded BIGINT NOT NULL,
  item_weight DOUBLE PRECISION NOT NULL,
  FOREIGN KEY(score_run_id) REFERENCES score_runs(id),
  FOREIGN KEY(item_id) REFERENCES items(id)
);
CREATE TABLE IF NOT EXISTS score_run_dimensions (
  score_run_id BIGINT NOT NULL,
  dimension_code TEXT NOT NULL,
  construct TEXT NOT NULL,
  score DOUBLE PRECISION,
  answered_count BIGINT NOT NULL,
  eligible_count BIGINT NOT NULL,
  PRIMARY KEY(score_run_id, dimension_code),
  FOREIGN KEY(score_run_id) REFERENCES score_runs(id)
);
CREATE TABLE IF NOT EXISTS score_run_totals (
  score_run_id BIGINT NOT NULL,
  construct TEXT NOT NULL,
  total_score DOUBLE PRECISION,
  maturity_level_id BIGINT,
  PRIMARY KEY(score_run_id, construct),
  FOREIGN KEY(score_run_id) REFERENCES score_runs(id),
  FOREIGN KEY(maturity_level_id) REFERENCES maturity_levels(id)
);
CREATE TABLE IF NOT EXISTS dimension_scores (
  assessment_id BIGINT NOT NULL,
  dimension_code TEXT NOT NULL,
  construct TEXT NOT NULL,
  score DOUBLE PRECISION NOT NULL,
  answered_count BIGINT NOT NULL,
  eligible_count BIGINT NOT NULL,
  method_version TEXT NOT NULL,
  calculated_at BIGINT NOT NULL,
  PRIMARY KEY(assessment_id, dimension_code),
  FOREIGN KEY(assessment_id) REFERENCES assessments(id)
);
CREATE TABLE IF NOT EXISTS scores (
  assessment_id BIGINT,
  construct TEXT,
  dimension_code TEXT,
  score DOUBLE PRECISION NOT NULL,
  PRIMARY KEY(assessment_id, construct, dimension_code),
  FOREIGN KEY(assessment_id) REFERENCES assessments(id)
);
CREATE TABLE IF NOT EXISTS diagnostic_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id BIGINT NOT NULL,
  code TEXT NOT NULL,
  name_ar TEXT NOT NULL,
  dimensions TEXT NOT NULL,
  operator TEXT NOT NULL,
  threshold DOUBLE PRECISION NOT NULL,
  severity TEXT NOT NULL,
  confidence DOUBLE PRECISION NOT NULL,
  active BIGINT NOT NULL DEFAULT 1,
  UNIQUE(version_id, code),
  FOREIGN KEY(version_id) REFERENCES instrument_versions(id)
);
CREATE TABLE IF NOT EXISTS diagnostic_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id BIGINT NOT NULL,
  rule_id BIGINT NOT NULL,
  evidence_json TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  UNIQUE(assessment_id, rule_id),
  FOREIGN KEY(assessment_id) REFERENCES assessments(id),
  FOREIGN KEY(rule_id) REFERENCES diagnostic_rules(id)
);
CREATE TABLE IF NOT EXISTS recommendations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id BIGINT NOT NULL,
  dimension_code TEXT NOT NULL,
  problem TEXT NOT NULL,
  action TEXT NOT NULL,
  why_it_matters TEXT,
  implementation_guidance TEXT,
  suggested_owner TEXT,
  expected_impact TEXT NOT NULL DEFAULT 'HIGH',
  effort TEXT NOT NULL DEFAULT 'MEDIUM',
  time_horizon TEXT NOT NULL DEFAULT '31-90',
  kpi TEXT,
  evidence_source TEXT,
  active BIGINT NOT NULL DEFAULT 1,
  UNIQUE(version_id, dimension_code),
  FOREIGN KEY(version_id) REFERENCES instrument_versions(id)
);
CREATE TABLE IF NOT EXISTS assessment_recommendations (
  assessment_id BIGINT NOT NULL,
  recommendation_id BIGINT NOT NULL,
  priority_score DOUBLE PRECISION NOT NULL,
  gap DOUBLE PRECISION NOT NULL,
  rank BIGINT NOT NULL,
  rationale TEXT,
  PRIMARY KEY(assessment_id, recommendation_id),
  FOREIGN KEY(assessment_id) REFERENCES assessments(id),
  FOREIGN KEY(recommendation_id) REFERENCES recommendations(id)
);
CREATE TABLE IF NOT EXISTS roadmap_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id BIGINT NOT NULL,
  recommendation_id BIGINT,
  horizon TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  owner TEXT,
  status TEXT NOT NULL DEFAULT 'NOT_STARTED',
  target_date TEXT,
  impact TEXT,
  effort TEXT,
  kpi TEXT,
  sort_order BIGINT NOT NULL DEFAULT 0,
  FOREIGN KEY(assessment_id) REFERENCES assessments(id),
  FOREIGN KEY(recommendation_id) REFERENCES recommendations(id)
);
CREATE TABLE IF NOT EXISTS invitations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL,
  assessment_id BIGINT,
  email TEXT NOT NULL,
  full_name TEXT,
  job_title TEXT,
  department TEXT,
  role TEXT NOT NULL,
  token TEXT UNIQUE NOT NULL,
  status TEXT NOT NULL,
  expires_at BIGINT NOT NULL,
  created_by BIGINT NOT NULL,
  accepted_at BIGINT,
  FOREIGN KEY(organization_id) REFERENCES organizations(id),
  FOREIGN KEY(assessment_id) REFERENCES assessments(id)
);
CREATE TABLE IF NOT EXISTS participant_sessions (
  token TEXT PRIMARY KEY,
  participant_id BIGINT,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  assessment_id BIGINT NOT NULL,
  expires_at BIGINT NOT NULL,
  FOREIGN KEY(participant_id) REFERENCES participants(id),
  FOREIGN KEY(assessment_id) REFERENCES assessments(id)
);
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  type TEXT NOT NULL DEFAULT 'INFO',
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  target_url TEXT,
  read_at BIGINT,
  created_at BIGINT NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS user_settings (
  user_id BIGINT PRIMARY KEY,
  locale TEXT NOT NULL DEFAULT 'ar',
  email_notifications BIGINT NOT NULL DEFAULT 1,
  security_notifications BIGINT NOT NULL DEFAULT 1,
  FOREIGN KEY(user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id BIGINT NOT NULL,
  report_type TEXT NOT NULL,
  status TEXT NOT NULL,
  created_by BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  payload BYTEA,
  content_type TEXT,
  filename TEXT,
  sha256 TEXT,
  FOREIGN KEY(assessment_id) REFERENCES assessments(id)
);
CREATE TABLE IF NOT EXISTS research_exports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id BIGINT NOT NULL,
  format TEXT NOT NULL,
  data_origin TEXT NOT NULL,
  filters_json TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  payload BYTEA,
  content_type TEXT,
  filename TEXT,
  sha256 TEXT
);
CREATE TABLE IF NOT EXISTS data_quality_flags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id BIGINT NOT NULL,
  flag_type TEXT NOT NULL,
  severity TEXT NOT NULL,
  details TEXT,
  status TEXT NOT NULL DEFAULT 'OPEN',
  created_at BIGINT NOT NULL,
  UNIQUE(assessment_id, flag_type),
  FOREIGN KEY(assessment_id) REFERENCES assessments(id)
);
CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  action TEXT NOT NULL,
  entity TEXT NOT NULL,
  entity_id BIGINT,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_at BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS system_configuration (
  key TEXT PRIMARY KEY,
  value_json TEXT NOT NULL,
  updated_by BIGINT,
  updated_at BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS assessment_join_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  assessment_id BIGINT NOT NULL,
  organization_id BIGINT NOT NULL,
  created_by_user_id BIGINT,
  created_by_participant_id BIGINT,
  max_uses BIGINT NOT NULL DEFAULT 25,
  use_count BIGINT NOT NULL DEFAULT 0,
  active BIGINT NOT NULL DEFAULT 1,
  expires_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  FOREIGN KEY(assessment_id) REFERENCES assessments(id),
  FOREIGN KEY(organization_id) REFERENCES organizations(id),
  FOREIGN KEY(created_by_user_id) REFERENCES users(id),
  FOREIGN KEY(created_by_participant_id) REFERENCES participants(id)
);
CREATE INDEX IF NOT EXISTS idx_join_codes_assessment ON assessment_join_codes(assessment_id, active);
CREATE TABLE IF NOT EXISTS consultation_leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id BIGINT NOT NULL,
  organization_id BIGINT,
  participant_id BIGINT,
  participant_user_id BIGINT,
  full_name TEXT NOT NULL,
  organization_name TEXT,
  job_title TEXT,
  email TEXT NOT NULL,
  phone_e164 TEXT NOT NULL,
  preferred_contact_method TEXT,
  preferred_contact_time TEXT,
  consultation_topics TEXT NOT NULL DEFAULT '[]',
  notes TEXT,
  consent_to_contact BIGINT NOT NULL,
  contact_consent_version TEXT NOT NULL,
  contact_consent_at BIGINT NOT NULL,
  marketing_consent BIGINT NOT NULL DEFAULT 0,
  marketing_consent_at BIGINT,
  privacy_notice_version TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'ASSESSMENT_RESULTS',
  status TEXT NOT NULL DEFAULT 'NEW',
  assigned_consultant_id BIGINT,
  first_contacted_at BIGINT,
  scheduled_at BIGINT,
  closed_at BIGINT,
  closure_reason TEXT,
  idempotency_key TEXT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  deleted_at BIGINT,
  UNIQUE(assessment_id, email, phone_e164),
  UNIQUE(idempotency_key),
  FOREIGN KEY(assessment_id) REFERENCES assessments(id),
  FOREIGN KEY(organization_id) REFERENCES organizations(id),
  FOREIGN KEY(participant_id) REFERENCES participants(id),
  FOREIGN KEY(participant_user_id) REFERENCES users(id),
  FOREIGN KEY(assigned_consultant_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS consultation_lead_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  consultation_lead_id BIGINT NOT NULL,
  event_type TEXT NOT NULL,
  previous_status TEXT,
  new_status TEXT,
  note TEXT,
  actor_user_id BIGINT,
  created_at BIGINT NOT NULL,
  FOREIGN KEY(consultation_lead_id) REFERENCES consultation_leads(id),
  FOREIGN KEY(actor_user_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_consultation_leads_assessment ON consultation_leads(assessment_id);
CREATE INDEX IF NOT EXISTS idx_consultation_leads_org ON consultation_leads(organization_id);
CREATE INDEX IF NOT EXISTS idx_consultation_leads_status ON consultation_leads(status, created_at);
CREATE INDEX IF NOT EXISTS idx_consultation_leads_consultant ON consultation_leads(assigned_consultant_id, status);
CREATE INDEX IF NOT EXISTS idx_consultation_leads_email ON consultation_leads(email);
CREATE INDEX IF NOT EXISTS idx_consultation_leads_phone ON consultation_leads(phone_e164);
CREATE INDEX IF NOT EXISTS idx_consultation_lead_events_lead ON consultation_lead_events(consultation_lead_id, created_at);
CREATE INDEX IF NOT EXISTS idx_memberships_org ON memberships(organization_id, role);
CREATE INDEX IF NOT EXISTS idx_sessions_user_expiry ON sessions(user_id, expires_at);
CREATE INDEX IF NOT EXISTS idx_assessments_org_status ON assessments(organization_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_assessment_context_demographics ON assessment_context(sector, firm_size, region);
CREATE UNIQUE INDEX IF NOT EXISTS idx_participants_org_user ON participants(organization_id, user_id) WHERE user_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_participants_org_email ON participants(organization_id, lower(email)) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_consents_user_type_version ON consents(user_id, consent_type, consent_version) WHERE user_id IS NOT NULL AND participant_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_consents_participant_type_version ON consents(participant_id, consent_type, consent_version) WHERE participant_id IS NOT NULL AND user_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_responses_assessment ON responses(assessment_id, participant_id);
CREATE INDEX IF NOT EXISTS idx_dimension_scores_assessment ON dimension_scores(assessment_id, construct);
CREATE INDEX IF NOT EXISTS idx_score_runs_assessment ON score_runs(assessment_id, is_current, created_at);
CREATE INDEX IF NOT EXISTS idx_invitations_token_status ON invitations(token, status);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON notifications(user_id, read_at);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_logs(entity, entity_id, created_at);

-- Additive columns introduced after schema version 4.
ALTER TABLE maturity_levels ADD COLUMN IF NOT EXISTS content_json TEXT;
ALTER TABLE instrument_versions ADD COLUMN IF NOT EXISTS product_status TEXT NOT NULL DEFAULT 'DRAFT';
ALTER TABLE instrument_versions ADD COLUMN IF NOT EXISTS scientific_status TEXT NOT NULL DEFAULT 'EVIDENCE_INFORMED';
ALTER TABLE instrument_versions ADD COLUMN IF NOT EXISTS scientific_status_changed_at BIGINT;
ALTER TABLE instrument_versions ADD COLUMN IF NOT EXISTS scientific_status_changed_by BIGINT;
ALTER TABLE dimensions ADD COLUMN IF NOT EXISTS content_json TEXT;
